### ISSUE TITLE
Legacy behaviors break with Bazel 0.22

### ISSUE THREAD

**Issue by OceanS2000** [ponyai/PublicCourse#17]
It seems that the `BUILD` files included in the repository contains some legacy features that has been removed in latest Bazel releases. They are causing problems in fresh environment:

1. In `WORKSPACE` file it specifies that
```
pony_http_archive(
    name = "com_google_protobuf",
    [...]
    strip_prefix = "protobuf-3.4.1",
[...]
```
But `protobuf-3.6.1.2` treats a incompatible problem with newest Bazel distributions (see [this issue of protobuf](https://github.com/protocolbuffers/protobuf/issues/5418)).
And the legacy version results in an error in building. (log
```
INFO: Invocation ID: cc933d2c-80a0-48e2-b9f0-860bbab7bdcd
ERROR: /home/username/.cache/bazel/_bazel_username/f6d6262dde2aef304ff6e84d454b7524/external/com_google_protobuf/BUILD:621:1: Traceback (most recent call last):
	File "/home/username/.cache/bazel/_bazel_username/f6d6262dde2aef304ff6e84d454b7524/external/com_google_protobuf/BUILD", line 621
		internal_gen_well_known_protos_java(srcs = WELL_KNOWN_PROTOS)
	File "/home/username/.cache/bazel/_bazel_username/f6d6262dde2aef304ff6e84d454b7524/external/com_google_protobuf/protobuf.bzl", line 268, in internal_gen_well_known_protos_java
		Label(("%s//protobuf_java" % REPOSITOR...))
	File "/home/ocean/.cache/bazel/_bazel_ocean/f6d6262dde2aef304ff6e84d454b7524/external/com_google_protobuf/protobuf.bzl", line 268, in Label
		REPOSITORY_NAME
builtin variable 'REPOSITORY_NAME' is referenced before assignment.
ERROR: /home/username/.cache/bazel/_bazel_username/f6d6262dde2aef304ff6e84d454b7524/external/com_google_protobuf/BUILD:397:1: Target '@com_google_protobuf//:android' contains an error and its package is in error and referenced by '@com_google_protobuf//:protoc'
ERROR: /home/username/PublicCourse/homework1/protobuf/proto/BUILD:14:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: Target '@com_google_protobuf//:protoc' contains an error and its package is in error
ERROR: Analysis of target '//homework1/protobuf:canvas_test' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.807s
INFO: 0 processes.
```

2. `WORKSPACE` also utilizes a custom `bazel:pony_http_archive.bzl` to get the dependencies. But this feature is now deprecated. As read in the log
```
INFO: Invocation ID: f53ca6bf-9454-40ba-8271-7b9d3f74e70f
ERROR: /home/ocean/PublicCourse/utils/testing/BUILD:3:1: no such package '@googletest//': The native new_http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule. and referenced by '//utils/testing:test_main'
ERROR: Analysis of target '//homework1/unittest:car_test' failed; build aborted: no such package '@googletest//': The native new_http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
INFO: Elapsed time: 53.181s
INFO: 0 processes.
```
So I have to add a `--incompatible_remove_naive_http_archive=false` when invoking `bazel`.
Through it is a valid workaround, it is possible to update these files?

=====

My `bazel version` is
```
INFO: Invocation ID: 683f39ef-4881-4ff1-89e9-ed9dad902b44
Build label: 0.22.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jan 28 19:53:21 2019 (1548705201)
Build timestamp: 1548705201
Build timestamp as int: 1548705201
```

**Comment by OceanS2000** [comment]
It seems that in Bazel 0.23, `new_http_archive` is completely removed 😭

**Comment by xuan-pony** [comment]
@OceanS2000 Thanks so much for pointing out the issue, and an extra bonus will be given to you for such contribution. 

Fixing the version issue may need non-trivial work, I have just updated the homework description to ask students to use `bazel 0.18.1`, which is the bazel version I can make sure everything works fine. Could you downgrade your bazel version if possible? Sorry for the trouble and extra effort to you.
